/**
 * WASM Loader Service
 * Loads and initializes the Lighter WASM module
 */

class WasmLoaderService {
  private static instance: WasmLoaderService;
  private wasmModule: any = null;
  private go: any = null;
  private initialized = false;
  private initializing = false;
  private initPromise: Promise<void> | null = null;

  private constructor() {}

  static getInstance(): WasmLoaderService {
    if (!WasmLoaderService.instance) {
      WasmLoaderService.instance = new WasmLoaderService();
    }
    return WasmLoaderService.instance;
  }

  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    if (this.initializing && this.initPromise) {
      return this.initPromise;
    }

    this.initializing = true;
    this.initPromise = this._doInitialize();
    
    try {
      await this.initPromise;
    } finally {
      this.initializing = false;
    }
  }

  private async _doInitialize(): Promise<void> {
    try {
      console.log('🚀 Loading WASM module...');

      // Load wasm_exec.js for Go WASM support
      await this.loadWasmExec();

      // @ts-ignore - Go is defined by wasm_exec.js
      this.go = new Go();

      // Fetch and instantiate WASM module
      const response = await fetch('/assets/sharedlib.wasm');
      const wasmBytes = await response.arrayBuffer();
      
      console.log('📦 WASM file loaded:', (wasmBytes.byteLength / 1024 / 1024).toFixed(2), 'MB');

      const result = await WebAssembly.instantiate(wasmBytes, this.go.importObject);
      this.wasmModule = result.instance;

      // Run the Go program
      this.go.run(this.wasmModule);

      // Wait for WASM functions to be available
      await new Promise(resolve => setTimeout(resolve, 100));

      this.initialized = true;
      console.log('✅ WASM module initialized successfully');
    } catch (error) {
      console.error('❌ Failed to initialize WASM:', error);
      throw error;
    }
  }

  private async loadWasmExec(): Promise<void> {
    return new Promise((resolve, reject) => {
      // Check if Go is already defined
      if (typeof (window as any).Go !== 'undefined') {
        resolve();
        return;
      }

      const script = document.createElement('script');
      script.src = '/assets/wasm_exec.js';
      script.onload = () => resolve();
      script.onerror = () => reject(new Error('Failed to load wasm_exec.js'));
      document.head.appendChild(script);
    });
  }

  isInitialized(): boolean {
    return this.initialized;
  }

  // WASM function wrappers
  generateAPIKey(seed?: string): { privateKey: string; publicKey: string } {
    if (!this.initialized) {
      throw new Error('WASM not initialized');
    }

    // @ts-ignore - Generated by WASM
    const result = GenerateAPIKey(seed || '');
    return {
      privateKey: result.privateKey || result.str,
      publicKey: result.publicKey || ''
    };
  }

  createClient(
    url: string,
    privateKey: string,
    chainId: number,
    apiKeyIndex: number = 0,
    accountIndex: number = 1
  ): any {
    if (!this.initialized) {
      throw new Error('WASM not initialized');
    }

    // @ts-ignore - Generated by WASM
    return CreateClient(url, privateKey, chainId, apiKeyIndex, accountIndex);
  }

  signChangePubKey(pubKey: string, nonce: number): any {
    if (!this.initialized) {
      throw new Error('WASM not initialized');
    }

    // @ts-ignore - Generated by WASM
    return SignChangePubKey(pubKey, nonce);
  }

  createAuthToken(deadline: number = 0): any {
    if (!this.initialized) {
      throw new Error('WASM not initialized');
    }

    // @ts-ignore - Generated by WASM
    return CreateAuthToken(deadline);
  }
}

export const wasmLoader = WasmLoaderService.getInstance();

